### ISSUE TITLE
Dutch locale

### ISSUE THREAD

**Issue by boltgolt** [advancedfx/l10n#1]
I could do an nl-NL translation today

**Comment by dtugend** [comment]
Hi, that would be nice.
It has been added: https://l10n.advancedfx.org/nl/l10n/
Please make a (single) translation suggest, so I can approve you as translation manager.
Don't forget to make an issue when you contributed in contrib repo as said on Project Info, so you will be added to the credits.

**Comment by boltgolt** [comment]
Thanks! Single translation made for now

**Comment by dtugend** [comment]
Thank you. Set you as translation manager (so you can add other people / managers).
