### ISSUE TITLE
Please add hungarian

### ISSUE THREAD

**Issue by sterox-rover** [advancedfx/l10n#2]

**Comment by dtugend** [comment]
Hi. It has been added.
Please suggest at least one Hungarian translation, so I can make you translation manager.
Don't forget to make an issue in contrib repo as said in Project Info after you contributed, so you will be added to the credits.

**Comment by sterox-rover** [comment]
Thank you! I've made a suggestion.

**Comment by dtugend** [comment]
Thank you.

**Comment by dtugend** [comment]
Did you remove yourself accidentally or intentionally as manager for that language?
I re-added you, but if you don't want it, I'll remove it again.
