### ISSUE TITLE
 request new locale for italian language

### ISSUE THREAD

**Issue by negativepriority** [advancedfx/l10n#3]
as title says, i want help to translate HLAE to italian language but i need a new locale on https://l10n.advancedfx.org/projects/l10n/

**Comment by dtugend** [comment]
Hi.

Italian has been added.
Please suggest at least one translation, so I can make you translation manager (so you can approve translations yourself.)

With kind regards

**Comment by negativepriority** [comment]
Thank you very much, i suggest one translation, i suggest others later, i'm waiting to be translation manager

**Comment by dtugend** [comment]
Hi. Thank you for your efforts, made you translation Manager (it also allows to manage other people for the Italian team). If we forget to add you to / update you in the credits, please remind us! With kind regards.
